server:
  port: 8101
  # 添加服务器超时配置
  tomcat:
    connection-timeout: 300000  # 连接超时时间：5分钟
    max-keep-alive-requests: 100
    keep-alive-timeout: 300000  # 保持连接超时时间：5分钟
  # 添加请求超时配置
  servlet:
    session:
      timeout: 300m  # session超时时间：5分钟

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.159.163.234:3306/aiagent?useSSL=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&connectTimeout=300000&socketTimeout=300000&autoReconnect=true&maxReconnects=10&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Mian2002@lmn
    hikari:
      connection-timeout: 300000  # 连接超时时间：5分钟
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000  # 空闲连接超时时间：5分钟
      max-lifetime: 600000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 0
      register-mbeans: true
      # 添加Hikari连接池日志配置
      pool-name: HikariPool-aiagent
      leak-detection-threshold: 60000
      # 添加连接池监控
      metrics-registry-name: aiagent
  # 添加SQL日志配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  # 添加日志配置
  logging:
    level:
      com.zaxxer.hikari: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.yupi.springbootinit: DEBUG
  # Elasticsearch 配置
  elasticsearch:
    uris: http://139.159.163.234:9200
    username: root
    password: Mian2002@lmn
    # 添加ES超时配置
    connection-timeout: 300000  # 连接超时时间：5分钟
    socket-timeout: 300000      # 套接字超时时间：5分钟

# 添加Feign客户端超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 300000  # 连接超时时间：5分钟
        readTimeout: 300000     # 读取超时时间：5分钟

# 添加Ribbon超时配置
ribbon:
  ReadTimeout: 300000  # 读取超时时间：5分钟
  ConnectTimeout: 300000  # 连接超时时间：5分钟

mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
    map-underscore-to-camel-case: false
    # 配置类型处理器
    type-handlers-package: com.yupi.springbootinit.config
    # 配置默认枚举类型处理器
    default-enum-type-handler: com.yupi.springbootinit.config.EducationEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
      # 主键类型
      id-type: auto
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456

# JWT配置
jwt:
  secret: aiagent-jwt-secret-key-2024-06-08-8101 