-- 添加缺失的列到 question 表
ALTER TABLE question 
ADD COLUMN userId BIGINT COMMENT '创建用户 id',
ADD COLUMN createTime datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
ADD COLUMN updateTime datetime DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN isDelete tinyint DEFAULT 0 NOT NULL COMMENT '是否删除'; 